'use strict';
const $=id=>document.getElementById(id);
const KEY='per-practice-v1';
let bank=[],session=[],index=0,chosen=null,checked=false,sessionCorrect=0,sessionWrong=0;
const blank=()=>({answered:0,correct:0,incorrect:0,wrongIds:[]});
let progress=readProgress();
function readProgress(){try{const p=JSON.parse(localStorage.getItem(KEY));if(p&&Array.isArray(p.wrongIds))return {...blank(),...p}}catch{}return blank()}
function save(){localStorage.setItem(KEY,JSON.stringify(progress));showSaved()}
function showSaved(){$('saved').textContent=`${progress.answered} respondidas · ${progress.correct} correctas`}
function screen(name){for(const id of ['start','practice','finish'])$(id).classList.toggle('hidden',id!==name)}
function available(){const topic=$('topic').value;const mode=$('mode').value;const n=bank.filter(q=>(topic==='all'||q.topic===topic)&&(mode!=='incorrect'||progress.wrongIds.includes(q.id))).length;$('available').textContent=`${n} ${n===1?'pregunta disponible':'preguntas disponibles'}`;$('begin').disabled=!n;return n}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function start(mode=$('mode').value){const topic=$('topic').value;session=bank.filter(q=>(topic==='all'||q.topic===topic)&&(mode!=='incorrect'||progress.wrongIds.includes(q.id)));if(mode==='random')shuffle(session);if(!session.length){$('start-message').textContent='No hay preguntas disponibles en esta selección.';screen('start');return}index=0;sessionCorrect=0;sessionWrong=0;screen('practice');render()}
function render(){const q=session[index];chosen=null;checked=false;$('position').textContent=`Pregunta ${index+1} de ${session.length}`;$('score').textContent=`${sessionCorrect} correctas · ${sessionWrong} incorrectas`;$('bar-fill').style.width=`${100*(index+1)/session.length}%`;$('question-topic').textContent=`${q.topic} · ${q.source} · pregunta ${q.number}`;$('question-text').textContent=q.question;const fig=$('question-figure');fig.replaceChildren();if(q.figure){const details=document.createElement('details');details.className='source-figure';const summary=document.createElement('summary');summary.textContent='Ver figura o recorte original del PDF';const img=document.createElement('img');img.src='./'+q.figure;img.alt='Fragmento original de la pregunta';img.loading='lazy';details.append(summary,img);details.open=/dibuix|dibujo|figura|imatge|imagen|esquema|representad|mostra|muestra|gràfic|gráfico/i.test(q.question);fig.append(details)}const choices=$('choices');choices.replaceChildren();for(const [letter,value] of Object.entries(q.choices)){const label=document.createElement('label');label.className='choice';label.dataset.letter=letter;const input=document.createElement('input');input.type='radio';input.name='answer';input.value=letter;input.addEventListener('change',()=>{if(checked)return;chosen=letter;$('check').disabled=false;choices.querySelectorAll('.choice').forEach(x=>x.classList.toggle('checked',x.dataset.letter===letter))});const span=document.createElement('span');span.textContent=`${letter.toUpperCase()}) ${value}`;label.append(input,span);choices.append(label)}$('check').disabled=true;$('check').classList.remove('hidden');$('next').classList.add('hidden');$('next').textContent=index+1===session.length?'Ver resultados':'Siguiente pregunta';$('feedback').className='feedback hidden';$('feedback').textContent='';window.scrollTo({top:0,behavior:'instant'})}
function check(){if(checked||!chosen)return;checked=true;const q=session[index],correct=chosen===q.correct;progress.answered++;if(correct){progress.correct++;sessionCorrect++;progress.wrongIds=progress.wrongIds.filter(id=>id!==q.id)}else{progress.incorrect++;sessionWrong++;if(!progress.wrongIds.includes(q.id))progress.wrongIds.push(q.id)}save();const inputs=$('choices').querySelectorAll('input');inputs.forEach(input=>{input.disabled=true;const label=input.closest('.choice');label.classList.add('disabled');if(input.value===q.correct)label.classList.add('correct');if(input.value===chosen&&!correct)label.classList.add('wrong')});const feedback=$('feedback');feedback.className='feedback '+(correct?'good':'bad');feedback.textContent=correct?'Correcto':`Incorrecto. La respuesta correcta es ${q.correct.toUpperCase()}) ${q.choices[q.correct]}`;$('score').textContent=`${sessionCorrect} correctas · ${sessionWrong} incorrectas`;$('check').classList.add('hidden');$('next').classList.remove('hidden');$('next').focus()}
function next(){if(!checked)return;if(++index<session.length)render();else finish()}
function finish(){screen('finish');const total=sessionCorrect+sessionWrong;const items=[['Respondidas',total],['Correctas',sessionCorrect],['Incorrectas',sessionWrong],['Porcentaje',`${total?Math.round(100*sessionCorrect/total):0}%`]];$('summary').replaceChildren(...items.map(([label,value])=>{const node=document.createElement('div');node.className='stat';const strong=document.createElement('strong');strong.textContent=value;const small=document.createElement('span');small.textContent=label;node.append(strong,small);return node}));$('retry').disabled=!progress.wrongIds.length}
$('mode').addEventListener('change',available);$('topic').addEventListener('change',available);$('begin').addEventListener('click',()=>start());$('check').addEventListener('click',check);$('next').addEventListener('click',next);$('exit').addEventListener('click',()=>{screen('start');available()});$('retry').addEventListener('click',()=>{$('topic').value='all';$('mode').value='incorrect';start('incorrect')});$('again').addEventListener('click',()=>{screen('start');available()});$('reset').addEventListener('click',()=>{if(!window.confirm('¿Borrar todas tus respuestas guardadas?'))return;progress=blank();save();available();$('start-message').textContent='Progreso borrado.'});
showSaved();fetch('./questions.json').then(r=>{if(!r.ok)throw Error('No se pudo abrir questions.json');return r.json()}).then(data=>{if(!Array.isArray(data)||!data.length)throw Error('El banco de preguntas está vacío');bank=data;const topics=[...new Set(bank.map(q=>q.topic).filter(Boolean))];for(const t of topics){const option=document.createElement('option');option.value=t;option.textContent=t;$('topic').append(option)}$('intro').textContent=`${bank.length} preguntas verificadas, organizadas por temas. Elegí cómo querés practicar.`;available()}).catch(e=>{$('intro').textContent='No se pudieron cargar las preguntas. Abrí esta página mediante un servidor local o GitHub Pages.';$('start-message').textContent=e.message});
